stages:
  download:
    cmd: kaggle datasets download -d zeerafle/sitting-posture -p data/original --unzip
    outs:
    - data/original:
        persist: true
        cache: false
  featurize:
    cmd: python src/featurize.py
    deps:
    - data/original
    - src/featurize.py
    outs:
    - data/data.csv:
        persist: true
    - data/poses_images_out:
        persist: true
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/data.csv
    - src/prepare.py
    outs:
    - data/processed
  train:
    foreach:
      - name: nn
        out: model.keras
      - name: adaboost
        out: adaboost.joblib
    do:
      cmd: python train.py
      wdir: src/models/${item.name}
      deps:
      - train.py
      - ../../../data/processed
      - ../../evaluate.py
      outs:
      - ${item.out}:
          cache: false
      metrics:
      - ../../../dvclive/${item.name}/metrics.json:
          cache: false
      plots:
      - ../../../dvclive/${item.name}/plots/metrics:
          cache: false
          x: step
      - ../../../dvclive/${item.name}/plots/images
