stages:
  # download:
  #   cmd: kaggle datasets download -d zeerafle/sitting-posture -p data/original --unzip
  #   outs:
  #   - data/original:
  #       persist: true
  #       cache: false
  featurize:
    cmd: uv run python src/featurize.py
    deps:
    - data/original
    - src/featurize.py
    outs:
    - data/data.csv:
        persist: true
    - data/poses_images_out:
        persist: true
  prepare:
    cmd: uv run python src/prepare.py
    deps:
    - data/data.csv
    - src/prepare.py
    outs:
    - data/processed

  train:
    foreach:
      - adaboost
      - nn
      - xgb
    do:
      cmd: uv run python train.py
      wdir: src/models/${item}
      deps:
      - train.py
      - ../../../data/processed
      - ../evaluate.py
      - ../utils.py
      params:
        - ../../../params.yaml:
      outs:
      - ../../../models/${item}:
          cache: false
      metrics:
      - ../../../dvclive/${item}/metrics.json:
          cache: false
      plots:
      - ../../../dvclive/${item}/plots/metrics:
          cache: false
          x: step
